server:
  port: '9080'
logging.level:
  root: info
  '[info.myone]': debug
  '[org.hibernate.SQL]': debug
  '[org.hibernate.type]': trace
# JWT
jwt:
  secret:
    VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
  datasource:
    url: jdbc:postgresql://localhost:5432/myone
    username: dikalee
    password: d09209233!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '4'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        "[format_sql]": true
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 'redis09233'
  output:
    ansi:
      enabled: always